# Generated by Django 6.0.4 on 2026-04-26 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('target_cgpa', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('credits', models.IntegerField()),
                ('semester', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmotionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stress_level', models.IntegerField(help_text='Scale 1-10')),
                ('sleep_hours', models.FloatField()),
                ('study_hours', models.FloatField()),
                ('motivation_score', models.IntegerField(help_text='Scale 1-10')),
                ('burnout_indicator', models.BooleanField(default=False)),
                ('date_logged', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotional_profiles', to='analytics.student')),
            ],
        ),
        migrations.CreateModel(
            name='ResultRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_marks', models.FloatField(default=0.0)),
                ('external_marks', models.FloatField(default=0.0)),
                ('attendance_percentage', models.FloatField(default=0.0)),
                ('assignment_score', models.FloatField(default=0.0)),
                ('final_score', models.FloatField(default=0.0)),
                ('pass_fail_status', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail')], max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='analytics.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.subject')),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
