# Generated by Django 6.0.4 on 2026-04-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_emotionalprofile_id_alter_resultrecord_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellnesschatmessage',
            name='mood_label',
            field=models.CharField(blank=True, choices=[('calm', 'Calm'), ('focused', 'Focused'), ('stressed', 'Stressed'), ('anxious', 'Anxious'), ('sad', 'Sad'), ('overwhelmed', 'Overwhelmed'), ('hopeful', 'Hopeful')], default='', help_text='Detected mood category for this user message', max_length=20),
        ),
        migrations.AddField(
            model_name='wellnesschatmessage',
            name='mood_score',
            field=models.FloatField(blank=True, help_text='Sentiment score from -1.0 (very negative) to +1.0 (very positive)', null=True),
        ),
        migrations.AlterField(
            model_name='emotionalprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='resultrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wellnesschatmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
